import React, { useState } from 'react';
import { PromptResult } from '../types';
import { CopyIcon, CheckIcon } from './Icons';

interface ResultDisplayProps {
  result: PromptResult;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ result }) => {
  const [activeTab, setActiveTab] = useState<'text' | 'json'>('text');
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const content = activeTab === 'text' 
      ? result.textPrompt 
      : JSON.stringify(result.jsonPrompt, null, 2);
      
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full bg-slate-900 border border-slate-700 rounded-2xl overflow-hidden flex flex-col h-full shadow-2xl">
      {/* Header / Tabs */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-slate-700 bg-slate-900/80 backdrop-blur-md sticky top-0 z-10">
        <div className="flex space-x-2 p-1 bg-slate-950 rounded-lg border border-slate-800">
          <button
            onClick={() => setActiveTab('text')}
            className={`px-4 py-1.5 rounded-md text-sm font-medium transition-all duration-200 ${
              activeTab === 'text' 
                ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-500/20' 
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            }`}
          >
            Text Prompt
          </button>
          <button
            onClick={() => setActiveTab('json')}
            className={`px-4 py-1.5 rounded-md text-sm font-medium transition-all duration-200 ${
              activeTab === 'json' 
                ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-500/20' 
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            }`}
          >
            JSON Data
          </button>
        </div>
        
        <button 
          onClick={handleCopy}
          className="flex items-center space-x-2 text-xs font-semibold uppercase tracking-wider text-slate-400 hover:text-white transition-colors p-2 rounded-lg hover:bg-slate-800"
        >
          {copied ? <CheckIcon className="w-4 h-4 text-emerald-400" /> : <CopyIcon className="w-4 h-4" />}
          <span>{copied ? 'Copied' : 'Copy'}</span>
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-6 relative bg-slate-900">
        {activeTab === 'text' ? (
          <div className="prose prose-invert max-w-none">
             <p className="text-lg leading-relaxed text-slate-300 whitespace-pre-wrap font-sans">
              {result.textPrompt}
             </p>
          </div>
        ) : (
          <pre className="font-mono text-sm text-emerald-400 overflow-x-auto">
            <code>
              {JSON.stringify(result.jsonPrompt, null, 2)}
            </code>
          </pre>
        )}
      </div>

      {/* Footer Hint */}
      <div className="px-6 py-3 bg-slate-950 border-t border-slate-800 text-xs text-slate-500 flex justify-between items-center">
        <span>Generated by Gemini Vision</span>
        <span>{activeTab === 'text' ? `${result.textPrompt.length} chars` : 'Structured Data'}</span>
      </div>
    </div>
  );
};

export default ResultDisplay;